#!/usr/bin/env bash
mkdir /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG100.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1001.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10013.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1010.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10162.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10291.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1034.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10365.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10418.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1046.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10494.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10530.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10609.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10643.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10731.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10754.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10817.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10873.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG10875.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG11161.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG11272.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG11308.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1131.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1136.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG11732.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG11752.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG11852.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1195.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12056.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1206.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12123.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12220.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12353.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12536.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12595.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12610.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12639.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12817.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12853.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG12864.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1289.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG13185.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG13186.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG133.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG13324.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG13349.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG13353.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG13405.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG13563.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1378.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG13930.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14032.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14044.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14101.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14267.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14351.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14388.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1439.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14529.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14643.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14645.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14684.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1483.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG149.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG14961.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG15117.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG15230.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG15327.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG15459.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG15670.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1595.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1627.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1628.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG16323.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG16572.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG16673.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG16866.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG16947.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1696.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1734.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG17341.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG17462.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1759.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG17708.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG17806.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG17891.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1797.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1802.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG18346.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG1879.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG19009.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG19219.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2000.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG20167.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG20379.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG20465.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG20882.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2113.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG21469.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG21696.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG21787.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2210.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2250.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG22682.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG22835.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2296.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG23048.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG23113.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG23315.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG23400.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG23580.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG237.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2373.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG23768.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG23879.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG24221.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG24585.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2467.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2535.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2541.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2556.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2572.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2582.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2584.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG25865.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG25923.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2601.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2618.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2627.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG26412.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG267.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG26940.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2707.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG27287.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG27500.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2753.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2771.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2773.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG27859.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2790.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2796.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG27965.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG28368.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2862.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG28802.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG28958.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2897.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG2929.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG293.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3024.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3042.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG30665.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3116.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3159.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG31692.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG31804.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3282.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG32927.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3323.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG33967.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3467.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3560.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3628.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3757.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3770.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3869.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG39601.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG3991.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4057.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG40608.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4153.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4198.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4211.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4221.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4223.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4232.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG42673.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4272.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG436.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG439.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4402.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4408.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4439.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4447.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4469.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG45920.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4657.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG46873.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4754.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG48365.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG48478.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG495.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG4981.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5092.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5119.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5126.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5164.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5258.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5281.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5307.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5330.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5453.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG555.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5567.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5638.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5670.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG571.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5713.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5764.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5832.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG598.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG5982.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6062.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6122.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6123.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6271.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6285.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6312.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6314.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6316.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6359.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6370.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6446.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6461.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6609.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6621.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6622.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6663.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6733.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6811.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG6991.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG70.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG7086.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG716.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG744.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG7449.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG748.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG7540.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG7625.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG7839.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG7854.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG7912.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8061.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8064.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8143.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8200.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8256.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8281.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8325.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG842.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8527.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8534.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8651.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8749.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8779.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG883.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG8932.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG909.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9123.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9179.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9231.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9481.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9487.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9644.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9691.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG978.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9787.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9822.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9881.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9891.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9910.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/
cp OG9927.fa /data/SBCS-BuggsLab/Josiah/OrthologousGroups/phylogenetic_guides/