D:\josiah\Projects\DDV\build\DDV.exe --fasta="D:\Genomes\Ash Finished Genomes\FRAX14_CLC_SSPACE_GAPCLOSER.fasta" --outname="F. americana (FRAX14)"
D:\josiah\Projects\DDV\build\DDV.exe --fasta="D:\Genomes\Ash Finished Genomes\FRAX15_CLC_SSPACE_GAPCLOSER.fasta" --outname="F. angustifolia subsp. oxycarpa  (FRAX15)"
D:\josiah\Projects\DDV\build\DDV.exe --fasta="D:\Genomes\Ash Finished Genomes\FRAX16_CLC_SSPACE_GAPCLOSER.fasta" --outname="F. angustifolia subsp. syriaca (FRAX16)"
D:\josiah\Projects\DDV\build\DDV.exe --fasta="D:\Genomes\Ash Finished Genomes\FRAX19_CLC_SSPACE_GAPCLOSER.fasta" --outname="F. goodingii (FRAX19)"
D:\josiah\Projects\DDV\build\DDV.exe --fasta="D:\Genomes\Ash Finished Genomes\FRAX20_CLC_SSPACE_GAPCLOSER.fasta" --outname="F. greggii (FRAX20)"
D:\josiah\Projects\DDV\build\DDV.exe --fasta="D:\Genomes\Ash Finished Genomes\FRAX21_CLC_SSPACE_GAPCLOSER.fasta" --outname="F. griffithii (FRAX21)"
D:\josiah\Projects\DDV\build\DDV.exe --fasta="D:\Genomes\Ash Finished Genomes\FRAX23_CLC_SSPACE_GAPCLOSER.fasta" --outname="F. nigra (FRAX23)"
D:\josiah\Projects\DDV\build\DDV.exe --fasta="D:\Genomes\Ash Finished Genomes\FRAX25_CLC_SSPACE_GAPCLOSER.fasta" --outname="F. xanthoxyloides (FRAX25)"
D:\josiah\Projects\DDV\build\DDV.exe --fasta="D:\Genomes\Ash Finished Genomes\FRAX26_CLC_SSPACE_GAPCLOSER.fasta" --outname="F. albicans (FRAX26)"
