#!/bin/sh
#$ -cwd           # Set the working directory for the job to the current directory
#$ -V
#$ -j y           # Merge the standard output and standard error
#$ -m aes
#$ -M josiah.seaman@gmail.com
#$ -l h_rt=08:0:0 # Request runtime
#$ -pe smp 20      # Request 1 CPU cores
#$ -l h_vmem=8G   # Request GB RAM  previous job was aborted at 83GB of memory

module load python/3.6.3
module load perl5lib
source /data/SBCS-BuggsLab/Josiah/DNA_Duplications/script_env/bin/activate
python /data/SBCS-BuggsLab/Josiah/DNA_Duplications/scaffolding.py FRAX01 FRAX01_Oct2017_800bp_HiSeq2500 /data/SBCS-BuggsLab/Josiah/Liverpool_800bp_HiSeq2500/FRAX01__HiSeq2500_800bp__34_file__SIMPLE__bubble_5000__assembly.fa extend
