#!/bin/sh
#$ -cwd           # Set the working directory for the job to the current directory
#$ -V
#$ -j y           # Merge the standard output and standard error
#$ -m aes
#$ -M josiah.seaman@gmail.com
#$ -l h_rt=16:0:0 # Request runtime
#$ -pe smp 4      # Request 1 CPU cores
#$ -l h_vmem=10G   # Request GB RAM

module load python/3.6.3
module load perl5lib
source /data/SBCS-BuggsLab/Josiah/DNA_Duplications/script_env/bin/activate
python /data/SBCS-BuggsLab/Josiah/DNA_Duplications/scaffolding.py FRAX11 FRAX11_800bp_HiSeq2500 /data/SBCS-BuggsLab/Josiah/Liverpool_800bp_HiSeq2500/FRAX11__HiSeq2500_800bp__42_file__SIMPLE__bubble_5000__asssembly.fa
