#!/bin/sh
#$ -cwd           # Set the working directory for the job to the current directory
#$ -V
#$ -j y           # Merge the standard output and standard error
#$ -m aes
#$ -M josiah.seaman@gmail.com
#$ -l h_rt=12:0:0 # Request runtime
#$ -pe smp 8      # Request 1 CPU cores
#$ -l h_vmem=20G   # Request GB RAM

module load soapdenovo2
GapCloser -a /data/SBCS-BuggsLab/Josiah/scaffolding/FRAX09_Oct2017_filtered/FRAX09_Oct2017_filtered.final.scaffolds.fasta \
 -b /data/SBCS-BuggsLab/Josiah/DNA_Duplications/data/FRAX09-GapCloser.config \
 -o FRAX09_Oct2017_filtered__GAPCLOSER \
 -t 8 > /data/SBCS-BuggsLab/Josiah/scaffolding/FRAX09_Oct2017_filtered.log 2>&1