#!/bin/sh
#$ -cwd           # Set the working directory for the job to the current directory
#$ -V
#$ -j y           # Merge the standard output and standard error
#$ -m aes
#$ -M josiah.seaman@gmail.com
#$ -l h_rt=08:0:0 # Request runtime
#$ -pe smp 20      # Request 1 CPU cores
#$ -l h_vmem=4G   # Request GB RAM

module load python/3.4.3
module load perl5lib
python /data/SBCS-BuggsLab/Josiah/DNA_Duplications/scaffolding.py FRAX09 FRAX09_Oct2017_draft_80GB /data/SBCS-BuggsLab/Josiah/Liverpool_800bp_HiSeq2500/FRAX09__Oct2017_draft__GC_filtered_56__no_mito_or_plastid.fa
