#!/bin/sh
#$ -cwd           # Set the working directory for the job to the current directory
#$ -V
#$ -j y           # Merge the standard output and standard error
#$ -m aes
#$ -M josiah.seaman@gmail.com
#$ -l h_rt=01:0:0 # Request runtime
#$ -pe smp 2      # Request 1 CPU cores
#$ -l h_vmem=1G   # Request GB RAM

module load python/3.6.3
module load perl5lib
source /data/SBCS-BuggsLab/Josiah/DNA_Duplications/script_env/bin/activate
python /data/SBCS-BuggsLab/Josiah/DNA_Duplications/scaffolding.py FRAX01 FRAX01_test /data/SBCS-BuggsLab/Josiah/Liverpool_800bp_HiSeq2500/FRAX01__HiSeq2500_800bp__34_file__SIMPLE__bubble_5000__assembly.fa
